import esbuild from 'esbuild';
import { readFileSync } from 'fs';

const isProduction = process.argv.includes('production');

const banner = `
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

esbuild.build({
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
  ],
  format: 'cjs',
  minify: isProduction,
  sourcemap: isProduction ? false : 'inline',
  banner: {
    js: banner,
  },
  outfile: 'main.js',
  define: {
    'process.env.NODE_ENV': JSON.stringify(isProduction ? 'production' : 'development'),
  },
  logLevel: 'info',
}).catch(() => process.exit(1));